---
title: ""
output: 
  html_document:
    css: !expr here::here("www", "web_report_trust.css")
---

# Frequently Asked Questions

```{r, echo = FALSE}
cur_date <- Sys.Date()
```

<center>**Last Updated:** `r cur_date`</center>
<br><br>

**Who created this dashboard?**
This dashboard was created by the Urban Institute in partnership with the Chicago Community Trust. This work is supported by the Kresge Foundation. 

**Why was this dashboard created, and how can it be used?**
This dashboard was created to track funds flowing through Chicago, Cook County, and Illinois governments for COVID-19 response, and to capture economic recovery programs relevant to the Chicago Community Trust’s institutional priority areas. The dashboard can be used by community stakeholders, policy researchers, and those interested in learning more about COVID-19 recovery to learn about funding allocations and spending priorities across different jurisdictions.

**Where does the information in this dashboard come from?**
Allocation and expenditure data are compiled from federal agency reports and public spending plans and budget reports from our three geographies of focus: Chicago, Cook County, and Illinois. For each program, the individual data source and source links are listed in the programs table.

**What federal recovery dollars are reflected in this dashboard?**
This dashboard reflects the subset of funds from the American Rescue Plan Act (ARPA), the Coronavirus Aid, Relief, and Economic Security Act (CARES), and the Coronavirus Response and Relief Supplemental Appropriations Act (CRRSAA) provided directly to Chicago, Cook County, and Illinois that align with the priority policy areas identified by the Chicago Community Trust. In the case of Chicago, the dashboard also reflects a local General Obligation Bond which the city paired with ARPA State and Local Fiscal Recovery Funds (SLFRF) in its Recovery Plan.

**What federal recovery dollars are not reflected in this dashboard?**
This dashboard does not include funds that flow directly from the federal government to public housing authorities, school districts or educational institutions, individuals and households, and nongovernmental organizations including nonprofit organizations and private sector businesses. The dashboard also does not include funds used for revenue replacement and operations. Additionally, some funds under SLFRF may fall under categories that do not reflect the Chicago Community Trust’s core priority policy areas of focus and are not captured in the dashboard. Finally, the current version of the dashboard does not include funds allocated to jurisdictions through the Infrastructure Investment and Jobs Act (IIJA), which will be included in future dashboard updates.

**How did you select which funding programs to include?**
Selected programs reflect a subset of major federal economic recovery funds flowing directly to states, counties, and localities. For ARPA SLFRF, the Chicago Community Trust reviewed funding allocations across jurisdictions and selected programs that align with their institutional priority policy areas in supporting economic recovery: community investment, community safety, household investment, housing, and workforce development. We also include total amounts of CARES state and local discretionary funding for which we do not have more specific information on how the funds were spent. While it’s possible that some of these funds were used for purposes that fall outside of our identified policy areas, we chose to err on the side of inclusion until we can identify more precise information. The dashboard does not include the full list of funding allocations across Chicago, Cook County, and Illinois, which can be found in each jurisdictions’ respective recovery plans.

**What is the difference between ARPA and ARPA State and Local Fiscal Recovery Funds?**
The State and Local Fiscal Recovery Funds (SLFRF) program is an allocation within ARPA of $350 billion to state, local, and tribal governments across the country. While some ARPA funds can only be used for specific purposes, such as emergency housing or small business assistance, SLFRF are flexible funds that state, county, and local governments can use for a wider range of programs to aid response to and recovery from COVID-19. A full list of applicable uses of SLFRF funds can be found on the U.S. Department of the Treasury website, and more information on each funding source in the dashboard can be found in the glossary.

**How did you select topics and subtopics to categorize funds?**
The dashboard categorizes funding allocations across five topics and twenty subtopics that map budget line items from local, county, and state recovery plans to the Chicago Community Trust’s priority policy areas and strategies in its work supporting inclusive recovery. See the glossary for a definition of each topic and subtopic included in the dashboard. The topics may change and may feature additional categories as new information on allocations and expenditures becomes available. 

**Will the dashboard feature expenditure data?**
The dashboard does not currently feature expenditure data, but will be updated with spending data for selected programs as information becomes available. Spending information can be pulled from public state, county, and local government expenditure reports, including legislative budget reports and mandatory recovery plan performance reports to the U.S. Treasury Department. Spending information for regional entities and tribal governments that received federal funding – which are not included in this dashboard – can be pulled in the same manner. Reporting requirements and deadlines vary by program.

**Why are some funding amounts not exact?**
The ARPA SLFRF-funded programs included in the dashboard are sourced from line item programs as listed by local, county, and state governments in public ARPA recovery plan reports. In some cases, these reports list multiple programs under one broad spending category, with one budget number for all programs—for instance, a public safety category may include three separate programs listed under one total budget number for all public safety initiatives, without allocations for each program. The “amount exact?” column indicates where we have split the total program budget evenly across multiple line items to generate an estimated average amount per program, and where we have pulled the exact budget number for one line item program.

**Why do program names and funding amounts not appear for all projects in the programs chart?**
The programs chart shows the subset of the total projects included in the dashboard matching the selected policy topic, jurisdiction, and/or legislation. The size of each project box in the chart is proportionate to the share of total funding shown in the chart represented by each project (e.g. if a project represents 10% of the total funding in the chart, the area of that project box will be 10% of the total chart area). For some combinations of policy topic, jurisdiction, and legislation, there are many projects displayed in the chart which forces the size of some projects with smaller funding amounts to be too small to display the project name and allocation. To view the name and allocation for those projects, you can either subset the project chart to a single law (ARPA, CARES, or CRRSAA) or you can view the programs description table.

**How were the programs in the “Explore Spending for Selected Programs” section at the bottom of the dashboard chosen?**
The dashboard features selected programs for which expenditure data at the zip code level is available. This section of the dashboard features a map and demographic information for zip codes receiving program funds, providing baseline information that users could apply towards their own analyses, such as equity assessments for specific programs. We are working to add more programs to this section as we identify more programs with zip code-level spending data available.

**Will the dashboard be updated?**
Yes. The dashboard will be updated on a continual basis as new information on fund allocations and expenditures becomes publicly available.
