---
title: ""
output: 
  html_document:
    number_sections: FALSE
    self_contained: TRUE
    code_folding: none
    toc: FALSE
    toc_float: FALSE
    css: !expr here::here("www", "web_report_trust.css")
editor_options:
  chunk_output_type: console
---

<center><h1>Frequently Asked Questions</h1></center> 

```{r, echo = FALSE}
cur_date <- Sys.Date()
```

<center>**Last Updated:** `r cur_date`</center> 


**Who created this dashboard?** 

This dashboard was created by the Urban Institute in partnership with the Chicago Community Trust. The Trust supplied information on target programs for inclusion, and Urban compiled and cleaned data to produce visualizations, charts, and tables, and developed code for the dashboard itself. 
 
**Where does the information in this dashboard come from?** 

Allocation and expenditure data are compiled from federal agency reports and public spending plans and budget reports from our three geographies of focus: Chicago, Cook County, and Illinois. For each program, the individual data source and source links are listed in the programs table. 
 
**What federal recovery dollars are reflected in this dashboard?** 

This dashboard reflects funds from the American Rescue Plan Act (ARPA), the Coronavirus Aid, Relief, and Economic Security Act (CARES), and the Coronavirus Response and Relief Supplemental Appropriations Act (CRRSAA). 
 
**How did you select which funding programs to include?** 

Selected programs reflect major federal economic recovery funds flowing directly to states, counties, and localities. For ARPA State and Local Fiscal Recovery Funds (SLFRF), the dashboard does not include the full list of funding allocations across Chicago, Cook County, and Illinois, instead highlighting programs related to the Chicago Community Trust’s priority programmatic topics and subtopics (see more below). 

**What is the difference between ARPA and ARPA State and Local Fiscal Recovery Funds?** 

The Coronavirus State and Local Fiscal Recovery Funds (SLFRF) program is an allocation within ARPA of $350 billion to state, local, and tribal governments across the country. While some ARPA funds can only be used for specific purposes, such as emergency housing, airport infrastructure, or small business assistance, SLFRF are flexible funds that subnational governments can use at their discretion to aid response to and recovery from Covid-19. A full list of applicable uses of SLFRF funds can be found on the U.S. Department of the Treasury website. 

**How did you select topics and subtopics to categorize funds?** 

The dashboard categorizes funding allocations across five topics and twenty subtopics reflecting budget categories from local, county, and state recovery plans, as well as the Chicago Community Trust’s priority policy areas and strategies in its work supporting inclusive recovery. The topics may change and may feature additional categories as new information on allocations and expenditures becomes available.  

**Why is some spending information missing?** 

Spending information is pulled from public state, county, and local government expenditure reports, including legislative budget reports and mandatory recovery plan performance reports to the U.S. Treasury Department as they become available. Different programs have different reporting requirements and deadlines, and the dashboard will be updated as reports are published. Project and expenditure reports for counties and cities must be submitted 30 days after the end of each quarter, and recovery plan and performance reports are due annually on July 31.1 

Missing spending data do not necessarily indicate that dollars have not been spent for a program.  

**Why are some funding amounts not exact?** 

The dashboard contains line item programs as listed by local, county, and state governments in public ARPA recovery plan reports. In some cases, these reports list multiple programs under one broad spending category, with one budget number for all programs—for instance, a public safety category may include three separate programs listed under one total budget number for all public safety initiatives, without allocations for each program. The “amount exact?” column indicates where we have split the total program budget evenly across multiple line items to generate an estimated average amount per program, and where we have pulled the exact budget number for one line item program. 

**How were “selected programs” chosen?** 

The dashboard features selected programs for which expenditure data is available and captures geographic information related to programmatic spending, such as small business assistance by zip code. This section of the dashboard features a map and demographic information for zip codes receiving program funds, providing baseline information that users could apply towards their own analyses, such as equity assessments for specific programs. 

**Will the dashboard be updated?** 

Yes. The dashboard will be updated on a continual basis by the Chicago Community Trust and the Urban Institute as new information on fund allocations and expenditures becomes publicly available. 